sudo: required
services:
  - docker

before_install:
  - docker build -t zerocoolcool/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run zerocoolcool/react-test npm test -- --coverage

after_success:
  - docker build -t zerocoolcool/multi-client ./client  
  - docker build -t zerocoolcool/multi-nginx ./nginx
  - docker build -t zerocoolcool/multi-server ./server
  - docker build -t zerocoolcool/multi-worker ./worker

#login to docker hub

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push zerocoolcool/multi-client
  - docker push zerocoolcool/multi-nginx
  - docker push zerocoolcool/multi-server
  - docker push zerocoolcool/multi-worker
